---
title: "Weather Information Preferences"
author: "Vipin"
date: "8/29/2020"
output: 
  ioslides_presentation:
    logo: images/sunstar.png
params:
  region:
    label: "Region"
    value: Mountain
    input: select
    choices: ["East North Central","East South Central",
          "Middle Atlantic","Mountain", "New England",
          "Pacific","South Atlantic", "West North Central",
          "West South Central"]
---


```{r, echo=FALSE, message=FALSE, warning=FALSE }
knitr::read_chunk("code/setup.R")
```

```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
```

```{r loadData}
```





``` {r child = "text/backgroundSection.Rmd"}
```

```{r child = "text/purposeSection.Rmd"}
```

## Demographics of Survey Respondents in a Merged Table

This section provides demographic summary tables for the `r nrow(sdat)` survey respondents.

```{r makeTable, code= readLines("code/makeTable.R")}
```


## Weather Source Preference by Gender

Finally, here is a breakdown of the `r nrow(sdat)` survey respondents for the `r params$region` region of the US on how they check their daily weather by gender.

```{r}
knitr::read_chunk("code/makeChart.R")

```

```{r makeCharts}
```








